import { useEffect, useState } from 'react';

import ProductDetail from '../../components/ProductDetail';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import ParticipantList from '../../components/ParticipantList';
import RoomInfo from '../../components/RoomInfo';
import axios from 'axios';
import { useState } from 'react';
import { useRouter } from 'next/dist/client/router';

import { useUser } from '../../context/user';
import { useRouter } from 'next/router';
import { getUIDUser, getAccessToken } from '../../services/Auth';
import { GIVEAWAY_LINK } from '../../config/giveaway';

const Event = () => {

  const user = useUser();
  const router = useRouter();
  const queryId = router.query.id;


  // State
  const [dataRoom, setRoomData] = useState({});
  const [dataBio, setDataBio] = useState({});
  const [isParticipant, setIsParticipant] = useState(false);
  const [participants, setParticipants] = useState({});
  const [isJoinGA, setIsJoinGA] = useState(false);
  const [totalParticipants, setTotalParticipants] = useState(1);
  const [finishTime, setFinishTime] = useState(0);

  const getProfileById = async () => {
    const userUID = getUIDUser();
    console.log(user.token);
    console.log(userUID);
    console.log(queryId);
    let response = await axios.get(
      `https://lepasaja-backend.herokuapp.com/api/v1/users/${userUID}`
    );

    let biodata = await response.data;
    setDataBio(biodata.data);
  }

  const getRoomById = async () => {
    let response = await axios.get(
      `https://lepasaja-backend.herokuapp.com/api/v1/rooms/${queryId}`
    );

    let room = await response.data;
    setRoomData(room.data);
    setParticipants(room.data.participants);
    setIsParticipant(true);
    setTotalParticipants(room.data.participants.length);
    await checkIsJoinRoom(room.data.participants);
    setFinishTime(room.data.finishAt*1000);
  }

  const checkIsJoinRoom = async (dataParticipants) => {
    dataParticipants.map((participant) => {
      if(participant.email === user.email){
        setIsJoinGA(true);
        return;
      }
    });
  }

  useEffect(() => {
    getRoomById();
    getProfileById();
    getUIDUser();
  }, []);


  const handleJoinRoom = (e) => {
    e.preventDefault();
    setIsJoinGA(true);
    
    axios
      .post
        (
          `https://lepasaja-backend.herokuapp.com/api/v1/rooms/${queryId}/join`,
          {user},
          {
            headers: {
              Authorization: getAccessToken()
            },
          }
        )
      .then(res => {
        console.log(res);
        console.log(res.data);
        router.replace(`/giveaway/${queryId}`);
      })
      .catch(err => console.log(err));
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main + `top-0 p-6`}>
          <ProductDetail roomInfo={dataRoom} handleJoinRoom={handleJoinRoom} isJoinRoom={isJoinGA}/>
          <div className="flex flex-row w-full">
            {!isParticipant ? (
              <div className='grow text-center'>Loading...</div>
            ) : (
              <ParticipantList participantLists={participants} />
            )}
            <RoomInfo totalParticipants={totalParticipants} finishTime={finishTime} />
          </div>
        </main>
      </div>
    </>
  );
};

export default Event;
